# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=30, verbose_name='Documento')),
                ('nacimiento', models.DateField(default=datetime.date.today, verbose_name='Nacimiento')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('caracteristicas', models.TextField(blank=True, null=True, verbose_name='Caracter\xedsticas')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar')),
                ('duracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duraci\xf3n')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Shows',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TipoEquipo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Especialidad'),
        ),
    ]
