# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171002_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Empleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Equipo')),
            ],
            options={
                'ordering': ('show',),
                'verbose_name_plural': 'Detalle Shows',
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='show',
            name='equipo',
        ),
        migrations.AddField(
            model_name='detalleshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Show'),
        ),
    ]
